---
title: "Exercise 1b"
author: "Kalin Nonchev"
date: "9/21/2021"
output: html_document
---

Now, let's proceed with the exercise!

Let's generate 100 random values from log-normal distribution wuth mu=1
and sigma=0.25:

```{r}
samples <- rlnorm(100, meanlog=1, sdlog=0.25)
```

Well done! Now we can create a histogram from this data:

```{r, echo=F}
# plot
hist(samples)
```

and from the log-transformed data:

```{r, echo=F}
# plot
hist(log(samples))
```

Let's find out the mean and the variance.

```{r}
samples.mean <- mean(samples) # mean
samples.mean
```

```{r}
samples.var <- var(samples) # variance
samples.var
```

... and from the log-transformed samples:

```{r}
log.samples.mean <- mean(log(samples)) # mean
log.samples.mean
```

```{r}
log.samples.var <- var(log(samples)) # variance
log.samples.var
```

```{r}
print(paste0("So finally, the mean and the variance from the samples is ", round(samples.mean, 2), " and ", round(samples.var, 2), ". When we log-transform the samples, we get a mean and variance of ", round(log.samples.mean, 2), " and ", round(log.samples.var, 2)))
```